### PR TITLE
Region codes for US/BR/AU/NO + fix to Norway Sor-Trondelag

### PR DESCRIPTION
**Pull request by sventech**
This is mainly region codes but a small fix to one region in Norway that was mangled.
Norway uses ISO-3166-2 numerical 2-digit codes internally for region abbreviations, and several other countries seem to as well. I think that standard could be a very fruitful source of data.

English Wikipedia list the names of regions in their native language / spelling for Latin-based alphabet countries (e.g., Norway, Brazil). Does that make sense for this selector?

I don't understand the status of Australia's "external regions" but I suspect they should be added.
The US military base regions don't have unique codes in some cases. Is that a problem?

NZ and GB are a bit complicated and I'll do them separately.

Relates to #2

### CODE REVIEW

**Comment by benkeen** [comment]
Ah, brilliant - thanks @sventech! Would you mind just editing the `data-with-abbrev.js` file for now? Once that's fully loaded with all abbreviations, I'll switch it out for the `data.js` file.

**Comment by benkeen** [comment]
> English Wikipedia list the names of regions in their native language / spelling for Latin-based alphabet countries (e.g., Norway, Brazil). Does that make sense for this selector?

I think that would be okay.

> I don't understand the status of Australia's "external regions" but I suspect they should be added.
The US military base regions don't have unique codes in some cases. Is that a problem?

Thanks for checking. They'll need to be unique, yes. Otherwise the script wouldn't be able to restore the correct value. 

I'm not wholly averse to adding our own custom (i.e. unique) value in this instance.

**Comment by sventech** [comment]
Sorry, the Norway change to the data.js is only a bug fix -- there was a mangled region name and two missing regions, not related to the abbreviations / region codes. Is that a problem?

**Comment by benkeen** [comment]
> Sorry, the Norway change to the data.js is only a bug fix -- there was a mangled region name and two missing regions, not related to the abbreviations / region codes. Is that a problem?

Oops, sorry. No, no problem.

> On the American military base region code system, sometimes the regions with the same code are grouped together so perhaps we could just have all entries with the same code combined.

Good call.

**Comment by benkeen** [comment]
Thanks @sventech!

**Pull request merged**
