### PR TITLE
Better New Zealand regions

### PR DESCRIPTION
**Pull request by micbenner**
The previous NZ regions were completely impractical and had some glaring absences (Auckland...)

I have updated the data file according to [this](http://www.tourism.org.nz/regions.html)  but am not setup to do the rest of the compiling 

Michael

### CODE REVIEW

**Comment by benkeen** [comment]
No worries, thanks micbenner! Curious why the PR shows all lines as having changed, but I'll merge and sort it out. Appreciated! :)

**Comment by micbenner** [comment]
Sorry, I'm a github noob. Probably just the way I edited it. Hope it's not too much trouble.

**Comment by benkeen** [comment]
Not at all! Probably just a newline issue.

**Comment by benkeen** [comment]
Hey @micbenner, I just did a quick diff and actually the NZ regions haven't changed! Mind giving it another go and seeing if you can create a new PR (or update this one) with the latest files? No worries if it's a pain - just copy & paste that line to this section and I'll update the record. 

Thanks, and sorry to be a pain.

**Comment by micbenner** [comment]
They should be

```
["New Zealand","NZ","Auckland|Bay of Plenty|Canterbury|Christchurch|Coromandel|Dunedin|Eastland|Fiordland|Hawke's Bay|Manawatu|Marlborough|Mt Cook|Nelson|Northland|Otago|Queenstown|Rotorua|Ruapehu|Ruapehu|Southland|Taranaki|Taupo|Waikato|Wairarapa|Wanaka|Wanganui|Wellington|West Coast"],
```

**Comment by benkeen** [comment]
Perfect, I'll update it now. Thanks again!

**Pull request merged**
